[package]
name = "rimuy/roselect"
description="Composable data selectors library"
version = "0.1.0"
license="MIT"
authors=["Rimuy"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
